#:schema node_modules/wrangler/config-schema.json
name = "print-toys"
compatibility_date = "2024-09-03"
pages_build_output_dir = "./build/client"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "print-toys"
database_id = "c58ab3a1-e076-461f-be78-d4d729ea0dad"
migrations_dir = "prisma/wrangler-migrations"