// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/typewriter": {
    params: {};
  };
  "/print-image": {
    params: {};
  };
  "/notetaker": {
    params: {};
  };
  "/actions/print-markdown": {
    params: {};
  };
  "/actions/print-image": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/typewriter" | "/print-image" | "/notetaker" | "/actions/print-markdown" | "/actions/print-image";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/typewriter.tsx": {
    id: "routes/typewriter";
    page: "/typewriter";
  };
  "routes/print-image.tsx": {
    id: "routes/print-image";
    page: "/print-image";
  };
  "routes/notetaker.tsx": {
    id: "routes/notetaker";
    page: "/notetaker";
  };
  "routes/actions.print-markdown.ts": {
    id: "routes/actions.print-markdown";
    page: "/actions/print-markdown";
  };
  "routes/actions.print-image.ts": {
    id: "routes/actions.print-image";
    page: "/actions/print-image";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/typewriter": typeof import("./app/routes/typewriter.tsx");
  "routes/print-image": typeof import("./app/routes/print-image.tsx");
  "routes/notetaker": typeof import("./app/routes/notetaker.tsx");
  "routes/actions.print-markdown": typeof import("./app/routes/actions.print-markdown.ts");
  "routes/actions.print-image": typeof import("./app/routes/actions.print-image.ts");
};